# -*- coding: utf-8 -*-
"""Untitled10.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19L7qiUTmDVX5ZJ-twY35LfCQO25Q3iVC
"""

!pip install spacy
!python -m spacy download en_core_web_sm


import spacy
from spacy.matcher import Matcher


def extract_keywords(address):

    nlp = spacy.load("en_core_web_sm")


    matcher = Matcher(nlp.vocab)

    pin_code_pattern = [{"SHAPE": "dddd"}, {"SHAPE": "d"}]
    matcher.add("PIN_CODE", [pin_code_pattern])

    proper_noun_pattern = [{"POS": "PROPN"}]
    matcher.add("PROPER_NOUN", [proper_noun_pattern])


    doc = nlp(address)

    keywords = set()


    matches = matcher(doc)
    for match_id, start, end in matches:
        keywords.add(doc[start:end].text)


    for ent in doc.ents:
        if ent.label_ in ["GPE", "LOC", "ORG"]:
            keywords.add(ent.text)

    return list(keywords)


addresses = [
    "PG in Kolkata",
]


for address in addresses:
    print(f"Address: {address}")
    print("Extracted Keywords:", extract_keywords(address))
    print("-" * 50)